
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: npm ci
  - name: Run Test
    init: npm run test
    command: npm run test
vscode:
  extensions:
    - bungcip.better-toml
    - esbenp.prettier-vscode
